if x < camera_get_view_border_x(view_camera[0])
	x = camera_get_view_border_x(view_camera[0])
if y < camera_get_view_border_y(view_camera[0])
	y = camera_get_view_border_y(view_camera[0])
if x > room_width-camera_get_view_border_x(view_camera[0])
	x = room_width-camera_get_view_border_x(view_camera[0])
if y > room_height-camera_get_view_border_y(view_camera[0])
	y = room_height-camera_get_view_border_y(view_camera[0])