draw_set_halign(fa_center)
draw_set_valign(fa_center)
draw_set_font(fnMenuButton)
draw_set_colour(c_maroon)
draw_roundrect(x1, y1, x2, y2, false)
draw_set_colour(c_ltgray)
draw_roundrect(x1, y1, x2, y2, true)
draw_text(x, y, button_text)